### ISSUE TITLE
how work with django-allauth 

### ISSUE THREAD

**Issue by ghost** [kbytesys/django-recaptcha3#5]

**Comment by trollmehard** [comment]
Create a custom form

```python
#forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField
from allauth.account.forms import SignupForm

class MyCustomSignupForm(SignupForm):
    """Custom SignUp form with captcha."""

    captcha = ReCaptchaField() 

    def save(self, request):
        # Ensure you call the parent classes save.
        # .save() returns a User object.
        user = super(MyCustomSignupForm, self).save(request)

        # Add additional stuff here if needed

        # You must return the original result.
        return user
```

If you want to do additional stuff you can also use the save method. Otherwise delete it.
Then follow the docs to implement the template tags.
As soon as you call `form.is_valid()` the recaptcha field should be validated as well which makes it not necessary to add any additional line of code in you views.

This is of course also not only possible for SignUp but as well as for Login and so on. See full list here: https://django-allauth.readthedocs.io/en/latest/forms.html

**Comment by ghost** [comment]
@trollmehard  thank you very much
